### ISSUE TITLE
第一次使用发现的问题

### ISSUE THREAD

**Issue by pengzhangzhi** [LibTraffic/Bigscity-LibTraffic#131]
感谢开源这么好的框架，第一次上手发现如下问题：
1. quick start 不详细，我按照quick start的教程开始做，python run_model.py 是运行不了的，因为没有指定参数。 而且你们没有说清楚需要下载哪些数据集之类的，让人找不到北。对新手不太友好。 之后运行python run_model.py --task traffic_state_pred --model DCRNN --dataset METR_LA的时候发现了很多安装包的问题，即使安装了requirements里面的包还是有很多包没覆盖到。 再次运行还是报错：代码import 库的时候是这样：import torch.tensor as tensor. 报错表示找不到tensor，修改为 from torch import tensor 解决了。

2.  到现在还是有问题没解决，torch-sparse 安装不上，我猜测是库和库之间依赖的问题！版本要对应起来！
网上的解决办法是：
pip install torch==1.2.0
pip install torch_geometric==1.4.1
pip install torch_sparse==0.4.4
pip install torch_scatter==1.4.0
pip install torch_cluster==1.4.5
但你们的torch版本很高，我怕重装torch会出现其他的版本兼容问题。
这个问题不知道该如何解决。
总之，你们的框架写的很全面，早上起来刷到你们，我被震惊了，很佩服！这么大的工作量，代码，数据，文档，还有网站等等一些工作，对技术要求也很高，你们做到了，敬佩难以言表，但是使用体验很差，望改进！
最后还是向你们致敬。

**Comment by WenMellors** [comment]
感谢您的反馈，我们会尽快排查 requirements 的问题

**Comment by WenMellors** [comment]
文档方面，我们也会尽快完善

**Comment by aptx1231** [comment]
再次感谢您的反馈。

- 针对您的反馈，我们对文档中关于[安装](https://bigscity-libtraffic-docs.readthedocs.io/en/latest/get_started/install.html)和[使用](https://bigscity-libtraffic-docs.readthedocs.io/en/latest/get_started/quick_start.html)的部分进行了完善，并且也将我们处理好的数据集进行了开源，同时也修改了本仓库的readme，请访问最新的文档进行查看。
- 关于requirements.txt中的部分问题和代码的一些问题也进行了修正，请拉取最新的代码。
- 关于torch-sparse这个库，由于我们其中一个模型STAGGCN的实现过程中使用了第三方库[torch-geometric](https://github.com/rusty1s/pytorch_geometric)，这个包的安装依赖比较复杂，其中就涉及到了torch-sparse。此前我们直接将它放在了requirements.txt，但是我发现它不能直接通过命令`pip install -r requirements.txt`进行简单的安装，而是需要根据自己的实际情况按照其[官方仓库](https://github.com/rusty1s/pytorch_geometric)的方法进行安装。目前没有太好的解决办法，只是将STAGGCN中对这个库进行import的语句注释掉了，如果您需要使用STAGGCN这个模型，请按照该官方仓库进行安装，并取消我加的那句注释，如果您不需要使用这个模型，则暂时可以忽略这个问题，不会影响LibTraffic的使用。之后我们会用更好的办法解决这个依赖问题。

最后，我们会持续完善LibTraffic，感谢您的使用，我们的Python版本为3.7.10，Pytorch版本为1.7.1，如果还会遇到其他问题请随时提问。

**Comment by pengzhangzhi** [comment]
> 再次感谢您的反馈。
> 
> 
> 
> - 针对您的反馈，我们对文档中关于[安装](https://bigscity-libtraffic-docs.readthedocs.io/en/latest/get_started/install.html)和[使用](https://bigscity-libtraffic-docs.readthedocs.io/en/latest/get_started/quick_start.html)的部分进行了完善，并且也将我们处理好的数据集进行了开源，同时也修改了本仓库的readme，请访问最新的文档进行查看。
> 
> - 关于requirements.txt中的部分问题和代码的一些问题也进行了修正，请拉取最新的代码。
> 
> - 关于torch-sparse这个库，由于我们其中一个模型STAGGCN的实现过程中使用了第三方库[torch-geometric](https://github.com/rusty1s/pytorch_geometric)，这个包的安装依赖比较复杂，其中就涉及到了torch-sparse。此前我们直接将它放在了requirements.txt，但是我发现它不能直接通过命令`pip install -r requirements.txt`进行简单的安装，而是需要根据自己的实际情况按照其[官方仓库](https://github.com/rusty1s/pytorch_geometric)的方法进行安装。目前没有太好的解决办法，只是将STAGGCN中对这个库进行import的语句注释掉了，如果您需要使用STAGGCN这个模型，请按照该官方仓库进行安装，并取消我加的那句注释，如果您不需要使用这个模型，则暂时可以忽略这个问题，不会影响LibTraffic的使用。之后我们会用更好的办法解决这个依赖问题。
> 
> 
> 
> 最后，我们会持续完善LibTraffic，感谢您的使用，我们的Python版本为3.7.10，Pytorch版本为1.7.1，如果还会遇到其他问题请随时提问。
> 
> 

谢谢您！回复很及时。不过我在想如果要做自己的框架是不是要尽量减少对别人框架的引用，自己造一些轮子方便些？不然自己的代码很容易收到别人影响

**Comment by aptx1231** [comment]
> > 再次感谢您的反馈。
> > 
> > * 针对您的反馈，我们对文档中关于[安装](https://bigscity-libtraffic-docs.readthedocs.io/en/latest/get_started/install.html)和[使用](https://bigscity-libtraffic-docs.readthedocs.io/en/latest/get_started/quick_start.html)的部分进行了完善，并且也将我们处理好的数据集进行了开源，同时也修改了本仓库的readme，请访问最新的文档进行查看。
> > * 关于requirements.txt中的部分问题和代码的一些问题也进行了修正，请拉取最新的代码。
> > * 关于torch-sparse这个库，由于我们其中一个模型STAGGCN的实现过程中使用了第三方库[torch-geometric](https://github.com/rusty1s/pytorch_geometric)，这个包的安装依赖比较复杂，其中就涉及到了torch-sparse。此前我们直接将它放在了requirements.txt，但是我发现它不能直接通过命令`pip install -r requirements.txt`进行简单的安装，而是需要根据自己的实际情况按照其[官方仓库](https://github.com/rusty1s/pytorch_geometric)的方法进行安装。目前没有太好的解决办法，只是将STAGGCN中对这个库进行import的语句注释掉了，如果您需要使用STAGGCN这个模型，请按照该官方仓库进行安装，并取消我加的那句注释，如果您不需要使用这个模型，则暂时可以忽略这个问题，不会影响LibTraffic的使用。之后我们会用更好的办法解决这个依赖问题。
> > 
> > 最后，我们会持续完善LibTraffic，感谢您的使用，我们的Python版本为3.7.10，Pytorch版本为1.7.1，如果还会遇到其他问题请随时提问。
> 
> 谢谢您！回复很及时。不过我在想如果要做自己的框架是不是要尽量减少对别人框架的引用，自己造一些轮子方便些？不然自己的代码很容易收到别人影响

是的，我们现在也意识到这个问题了，在后续的迭代中我们会把依赖第三方框架的模型全部重新实现，使得LibTraffic只依赖于基础的几个包。多谢！
