### ISSUE TITLE
task: traj_loc_pred; model: STRNN; dataset:foursquare_tky. can't run

### ISSUE THREAD

**Issue by Pumbaa-peng** [LibTraffic/Bigscity-LibTraffic#154]
I have read your code for a long time, thank you for your great job!  but, I think it has some bugs.
when I want to use STRNN to test trajectory location prediction with dataset--foursquare_tky, I get this bug:

File "/workdir/Bigscity-LibTraffic-master/libtraffic/model/trajectory_loc_prediction/STRNN.py", line 21, in __init__
    self.poi_profile = data_feature['poi_profile']
KeyError: 'poi_profile'

and I think the input format of STRNN has some problems too：
you used：
"dataset_class": "TrajectoryDataset",
 "executor": "TrajLocPredExecutor",
 "evaluator": "TrajLocPredEvaluator",
 "traj_encoder": "StandardTrajectoryEncoder"
I'm afraid they don't match，because I see there exists StrnnEncoder，but，I still can find the “data_feature['poi_profile']“

**Comment by WenMellors** [comment]
Thanks for your feedback. We have fixed this issue in our latest pull request. However, we have to remind you that the STRNN model has serious performance problems due to the use of unofficial open source code. In the future, we will re-implement this model only based on the paper.
